/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToolbar: typeof import('./src/components/appToolbar.vue')['default']
    GoalsCard: typeof import('./src/components/goalsCard.vue')['default']
    KanbanCard: typeof import('./src/components/kanbanCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
