/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KanbanCard: typeof import('./src/components/kanbanCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SprintGoals: typeof import('./src/components/sprintGoals.vue')['default']
    SprintTable: typeof import('./src/components/sprintTable.vue')['default']
  }
}
